# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrossplaneTraceExplorer < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/brunoluiz/crossplane-trace-explorer/releases/download/v1.0.0/crossplane-trace-explorer_Darwin_arm64.tar.gz"
      sha256 "9ad8f66be79d434946cce7855e7de909105aaa3fcf3070c80a7946a8322b1ee6"

      def install
        bin.install "crossplane-trace-explorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brunoluiz/crossplane-trace-explorer/releases/download/v1.0.0/crossplane-trace-explorer_Linux_x86_64.tar.gz"
        sha256 "24cae99406e4636ad37b66f77cdb0aab6b86a0fa2ddc64c8a5c1d30903c180d6"

        def install
          bin.install "crossplane-trace-explorer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brunoluiz/crossplane-trace-explorer/releases/download/v1.0.0/crossplane-trace-explorer_Linux_arm64.tar.gz"
        sha256 "6dd007825fc32084e858d071435966b0e0d8ded1e9d257a6cc148f9dd9f7b114"

        def install
          bin.install "crossplane-trace-explorer"
        end
      end
    end
  end
end
