# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrossplaneTraceExplorer < Formula
  desc ""
  homepage ""
  version "1.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/brunoluiz/crossplane-trace-explorer/releases/download/v1.1.0/crossplane-trace-explorer_Darwin_arm64.tar.gz"
      sha256 "d414e74cb5267914d33ab82fa175a3b7d358615dd18fecbda34b7c8c182fb955"

      def install
        bin.install "crossplane-trace-explorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brunoluiz/crossplane-trace-explorer/releases/download/v1.1.0/crossplane-trace-explorer_Linux_x86_64.tar.gz"
        sha256 "d5658228496d3935e0e115eda98cd6053edf41bee8eaa06829ffccec697bef40"

        def install
          bin.install "crossplane-trace-explorer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brunoluiz/crossplane-trace-explorer/releases/download/v1.1.0/crossplane-trace-explorer_Linux_arm64.tar.gz"
        sha256 "c8b0e863575432fa67b6db05cd49505486dfdb7cf7d7f7407a60f8e5350ba844"

        def install
          bin.install "crossplane-trace-explorer"
        end
      end
    end
  end
end
