# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrossplaneExplorer < Formula
  desc ""
  homepage ""
  version "1.6.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/brunoluiz/crossplane-explorer/releases/download/v1.6.0/crossplane-explorer_Darwin_arm64.tar.gz"
      sha256 "963d3bd19fbef5dabceb1d7081defdf32c1bb2b7ad68232f24e08b63b048c6ce"

      def install
        bin.install "crossplane-explorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brunoluiz/crossplane-explorer/releases/download/v1.6.0/crossplane-explorer_Linux_x86_64.tar.gz"
        sha256 "a6e6f66a424c958e6997ab8a9648686dd8b67bc80cd3fc702739e97665541807"

        def install
          bin.install "crossplane-explorer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brunoluiz/crossplane-explorer/releases/download/v1.6.0/crossplane-explorer_Linux_arm64.tar.gz"
        sha256 "6d56d0547e0fe01fea9bcc898f339b64d5ceb2d86490aafa31168ace42989ede"

        def install
          bin.install "crossplane-explorer"
        end
      end
    end
  end
end
