# This file was generated by GoReleaser. DO NOT EDIT.
class FlaggioCleanerBot < Formula
  desc ""
  homepage "https://github.com/brunoluiz/flaggio-cleaner-bot"
  version "1.0.3"
  

  if OS.mac?
    url "https://github.com/brunoluiz/flaggio-cleaner-bot/releases/download/v1.0.3/flaggio-cleaner-bot_1.0.3_darwin_amd64.tar.gz"
    sha256 "f26618549fca199e9728a62d2a5fcac645b0657efbc38ccf1965133d5eb75722"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brunoluiz/flaggio-cleaner-bot/releases/download/v1.0.3/flaggio-cleaner-bot_1.0.3_linux_amd64.tar.gz"
      sha256 "c1123259c9a4cda71a39763d6d8f88c1fee61d1d5cb7b8ab8e99375343bb7427"
    end
  end

  def install
    bin.install "flaggio-cleaner-bot"
  end
end
