# This file was generated by GoReleaser. DO NOT EDIT.
class FlaggioCleanerBot < Formula
  desc ""
  homepage "https://github.com/brunoluiz/flaggio-cleaner-bot"
  version "1.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/brunoluiz/flaggio-cleaner-bot/releases/download/v1.0.2/flaggio-cleaner-bot_1.0.2_darwin_amd64.tar.gz"
    sha256 "597e2ed8a333af0bdfd5e2e025dd75ad7bf4b7d55a7fce8ade1125b79bbf4505"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brunoluiz/flaggio-cleaner-bot/releases/download/v1.0.2/flaggio-cleaner-bot_1.0.2_linux_amd64.tar.gz"
      sha256 "fd804f126414d9251d7af9ff2de20f096c7f82f3515ba4073d949e8763f7a2b0"
    end
  end

  def install
    bin.install "flaggio-cleaner-bot"
  end
end
