# This file was generated by GoReleaser. DO NOT EDIT.
class GoPwaServer < Formula
  desc "🚀 Fast static server for your PWA applications"
  homepage "https://github.com/brunoluiz/go-pwa-server"
  version "0.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/brunoluiz/go-pwa-server/releases/download/v0.0.0/go-pwa-server_Darwin_x86_64.tar.gz"
    sha256 "4c6063067fcd39f8a6975fc0987db0c99345fcae078fc9216d817605192d1ddb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brunoluiz/go-pwa-server/releases/download/v0.0.0/go-pwa-server_Linux_x86_64.tar.gz"
      sha256 "531c1e3d8de40cb399d9261614a93c8c49bc472783eab01f6b2eee58f8e69ce8"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brunoluiz/go-pwa-server/releases/download/v0.0.0/go-pwa-server_Linux_arm64.tar.gz"
        sha256 "481642a39438dbc9bbaa68855d031698f42532c59bd9bde76a95a8be143e8346"
      else
        url "https://github.com/brunoluiz/go-pwa-server/releases/download/v0.0.0/go-pwa-server_Linux_armv6.tar.gz"
        sha256 "e1388f53124e3bf15ca669033b8f651bbe7ed3b750b31e6961dad77c49095fa6"
      end
    end
  end

  def install
    bin.install "go-pwa-server"
  end
end
