# This file was generated by GoReleaser. DO NOT EDIT.
class GoPwaServer < Formula
  desc "🚀 Fast static server for your PWA applications"
  homepage "https://github.com/brunoluiz/go-pwa-server"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/brunoluiz/go-pwa-server/releases/download/v1.0.0/go-pwa-server_1.0.0_darwin_amd64.tar.gz"
    sha256 "4f80544c5ac7b7551684095ac7bb749ab6a2a8d80bdad71329946040313ea9b0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brunoluiz/go-pwa-server/releases/download/v1.0.0/go-pwa-server_1.0.0_linux_amd64.tar.gz"
      sha256 "a9c9d01a1c531ab5a0ff07dcdff0e6d74db460f9e87e1b885da4d5894f96c4b7"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brunoluiz/go-pwa-server/releases/download/v1.0.0/go-pwa-server_1.0.0_linux_arm64.tar.gz"
        sha256 "67d0f088467837d09a5a7b716843f63e5a2d1fa00a03e23f30d6f4c74f95486e"
      else
        url "https://github.com/brunoluiz/go-pwa-server/releases/download/v1.0.0/go-pwa-server_1.0.0_linux_armv6.tar.gz"
        sha256 "693b6403e15572506f35c93145afd3bf9fa5550f13f84d94044e83a140340a94"
      end
    end
  end

  def install
    bin.install "go-pwa-server"
  end
end
