# This file was generated by GoReleaser. DO NOT EDIT.
class GoaccessPixel < Formula
  desc "Goaccess pixel track route"
  homepage "https://github.com/brunoluiz/goaccess-pixel"
  version "1.1.0"
  

  if OS.mac?
    url "https://github.com/brunoluiz/goaccess-pixel/releases/download/v1.1.0/goaccess-pixel_1.1.0_darwin_amd64.tar.gz"
    sha256 "80359a71afc4685290bfa6f55a9a2ea53715433d2e1962d64c49a34c2956dc48"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brunoluiz/goaccess-pixel/releases/download/v1.1.0/goaccess-pixel_1.1.0_linux_amd64.tar.gz"
      sha256 "1fd9da6a558e1c02c1ee83d07df1c17de46ffecae5edd2d838c3d22be962fae0"
    end
  end

  def install
    bin.install "goaccess-pixel"
  end
end
