# This file was generated by GoReleaser. DO NOT EDIT.
class GoaccessPixel < Formula
  desc "Goaccess pixel track route"
  homepage "https://github.com/brunoluiz/goaccess-pixel"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/brunoluiz/goaccess-pixel/releases/download/v1.0.0/goaccess-pixel_1.0.0_darwin_amd64.tar.gz"
    sha256 "656d628a74a3da241d3c58c186bbbe564185d263c9507858383ead022175253c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brunoluiz/goaccess-pixel/releases/download/v1.0.0/goaccess-pixel_1.0.0_linux_amd64.tar.gz"
      sha256 "f33283211c45e913b657bbbe44d56b417c58725d2ae96fc02134cdba0856ccd8"
    end
  end

  def install
    bin.install "goaccess-pixel"
  end
end
