# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jornada < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/brunoluiz/jornada/releases/download/v0.1.0/jornada_0.1.0_darwin_amd64.tar.gz"
    sha256 "7118685fb541e1dfde520f68e4d85b55c84e44adcf93103afd4ab3ec98c67b5e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/brunoluiz/jornada/releases/download/v0.1.0/jornada_0.1.0_linux_amd64.tar.gz"
    sha256 "b9379859d29db92acc392882426d7d502a451bd220cd84d0c7fbf4baba210ab7"
  end

  def install
    bin.install "jornada"
  end
end
