# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jornada < Formula
  desc ""
  homepage ""
  version "0.5.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/brunoluiz/jornada/releases/download/v0.5.0/jornada_0.5.0_darwin_amd64.tar.gz"
    sha256 "7976c01544e6e34c8d2b085a36353a812b569721232884c0feb6da28b85b2b7f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/brunoluiz/jornada/releases/download/v0.5.0/jornada_0.5.0_linux_amd64.tar.gz"
    sha256 "9464a0f1e639bdb3055eb99c323f2131cdec236c3744514548cb73ba32668594"
  end

  def install
    bin.install "jornada"
  end
end
