# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jornada < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/brunoluiz/jornada/releases/download/v0.1.0/jornada_0.1.0_darwin_amd64.tar.gz"
    sha256 "623ade1a254ac10bfa1d2b1592a7553a68883d397d99692278cf0bdc8c18efd3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/brunoluiz/jornada/releases/download/v0.1.0/jornada_0.1.0_linux_amd64.tar.gz"
    sha256 "fffe751e73a4ca756b8cbcbcb99755e4b7df311357c065a259cb555f89edeb2d"
  end

  def install
    bin.install "jornada"
  end
end
