# This file was generated by GoReleaser. DO NOT EDIT.
class MermaidServer < Formula
  desc ""
  homepage ""
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/brunoluiz/mermaid-server/releases/download/v1.1.0/mermaid-server_1.1.0_darwin_amd64.tar.gz"
    sha256 "ff958920da00dfe1ea18ca1fd0f6a461516e5f3c2a79f6122713490dde076dd6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brunoluiz/mermaid-server/releases/download/v1.1.0/mermaid-server_1.1.0_linux_amd64.tar.gz"
      sha256 "172181cf4016259888012b318c6625872d24c92779cfb16383fdae2ff411bfc8"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brunoluiz/mermaid-server/releases/download/v1.1.0/mermaid-server_1.1.0_linux_arm64.tar.gz"
        sha256 "691200edf83b5481244b19dd8b847bf5903bf191374260b2b4b378ae705869c3"
      else
        url "https://github.com/brunoluiz/mermaid-server/releases/download/v1.1.0/mermaid-server_1.1.0_linux_armv6.tar.gz"
        sha256 "820e838c8e7222e6b6b67eab1c818e53033b39d503b04d71ba326241fd098521"
      end
    end
  end

  def install
    bin.install "mermaid-server"
  end
end
