# This file was generated by GoReleaser. DO NOT EDIT.
class MermaidServer < Formula
  desc ""
  homepage ""
  version "1.3.0"
  

  if OS.mac?
    url "https://github.com/brunoluiz/mermaid-server/releases/download/v1.3.0/mermaid-server_1.3.0_darwin_amd64.tar.gz"
    sha256 "196d69a086ab00ef318b9b5a14dd993be4cd73c254ec104ca27683bdbde3c64a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brunoluiz/mermaid-server/releases/download/v1.3.0/mermaid-server_1.3.0_linux_amd64.tar.gz"
      sha256 "c1d835c6ce53c754868070bd52539824c4bac632698e7570228eb6cb1e8108ab"
    end
  end

  def install
    bin.install "mermaid-server"
  end
end
