# This file was generated by GoReleaser. DO NOT EDIT.
class MermaidServer < Formula
  desc ""
  homepage ""
  version "1.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/brunoluiz/mermaid-server/releases/download/v1.2.0/mermaid-server_1.2.0_darwin_amd64.tar.gz"
    sha256 "e2e98b009cf07fcac6915ea6fd64abfb2dacca191fe7231845e033d016e9bf56"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brunoluiz/mermaid-server/releases/download/v1.2.0/mermaid-server_1.2.0_linux_amd64.tar.gz"
      sha256 "aac5cfd3076f97f243f0194945103a9ba07a2f1755f26c539befa46f8ff96f9f"
    end
  end

  def install
    bin.install "mermaid-server"
  end
end
