# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monogo < Formula
  desc ""
  homepage ""
  version "1.8.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/brunoluiz/monogo/releases/download/v1.8.0/monogo_Darwin_arm64.tar.gz"
      sha256 "2942e396cd3084b0ccc72a93661b985b3ee141cd0f67bb6b7b412aa8f02c266f"

      def install
        bin.install "monogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brunoluiz/monogo/releases/download/v1.8.0/monogo_Linux_x86_64.tar.gz"
      sha256 "7d6a5931f0ff99c9fafa7543f108090f443e8450c6e8f5bc6a43aaa5830d928f"
      def install
        bin.install "monogo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brunoluiz/monogo/releases/download/v1.8.0/monogo_Linux_arm64.tar.gz"
      sha256 "0b9f020ba74a07a5584e2461d4b4e8935f528de2cc9d4fb3e5b15b50fcd4e852"
      def install
        bin.install "monogo"
      end
    end
  end
end
