# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monogo < Formula
  desc ""
  homepage ""
  version "1.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/brunoluiz/monogo/releases/download/v1.1.0/monogo_Darwin_arm64.tar.gz"
      sha256 "54692900893975da3548a63bd027c4f17d7f6da34a0a1bde2534e96d31fbf0a2"

      def install
        bin.install "monogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brunoluiz/monogo/releases/download/v1.1.0/monogo_Linux_x86_64.tar.gz"
      sha256 "ea7ce8548b57a3b39ce7c4d7dfefd9e65d3ffdaf0af911fc30ab2be0dfa871be"
      def install
        bin.install "monogo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brunoluiz/monogo/releases/download/v1.1.0/monogo_Linux_arm64.tar.gz"
      sha256 "47a7fbbccb2a98718468a95b3265529ad64c8286b86aa2e118abd4488ab6115e"
      def install
        bin.install "monogo"
      end
    end
  end
end
