# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monogo < Formula
  desc ""
  homepage ""
  version "1.7.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/brunoluiz/monogo/releases/download/v1.7.0/monogo_Darwin_arm64.tar.gz"
      sha256 "9d63e59c2a5c3ac9ec8efb229a9fdfe588523302e24629be81f555f82c74a4ce"

      def install
        bin.install "monogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brunoluiz/monogo/releases/download/v1.7.0/monogo_Linux_x86_64.tar.gz"
      sha256 "9f80ab2b7176c21153fa05ab072b0542acd5d0fe5404ffd8bc779bd2cf18fb00"
      def install
        bin.install "monogo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brunoluiz/monogo/releases/download/v1.7.0/monogo_Linux_arm64.tar.gz"
      sha256 "7c484479404ae2856d5de448d71a9280e347e74af149f605934a92c5d13d93b4"
      def install
        bin.install "monogo"
      end
    end
  end
end
