# This file was generated by GoReleaser. DO NOT EDIT.
class PwaServer < Formula
  desc "🚀 Fast static server for your PWA applications"
  homepage "https://github.com/brunoluiz/pwa-server"
  version "1.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/brunoluiz/pwa-server/releases/download/v1.1.1/pwa-server_1.1.1_darwin_amd64.tar.gz"
    sha256 "7f5199809942a0fb3e9d6eed6187d030a2d83c3a280a48d844c2579526f5df61"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brunoluiz/pwa-server/releases/download/v1.1.1/pwa-server_1.1.1_linux_amd64.tar.gz"
      sha256 "7c1e464dafd56b9e845fc326c628f70f79d16d69172acdd1a5dda854f9d20cbb"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brunoluiz/pwa-server/releases/download/v1.1.1/pwa-server_1.1.1_linux_arm64.tar.gz"
        sha256 "cd16b5d89a989605a3c5a13db6383a4a859f86e5dda6d23b3e612ab0e9eff3d6"
      else
        url "https://github.com/brunoluiz/pwa-server/releases/download/v1.1.1/pwa-server_1.1.1_linux_armv6.tar.gz"
        sha256 "7aba6bfe273dae7a3da26108329ce38152bdf711581380b33b36f32a734ee2da"
      end
    end
  end

  def install
    bin.install "pwa-server"
  end
end
