# This file was generated by GoReleaser. DO NOT EDIT.
class Urlzap < Formula
  desc ""
  homepage ""
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/brunoluiz/urlzap/releases/download/v0.1.0/urlzap_0.1.0_darwin_amd64.tar.gz"
    sha256 "c2dad8a0e00c5a9820a193d3c9aa1fddd7a3ec3c65912bab6bb328b527158fa8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brunoluiz/urlzap/releases/download/v0.1.0/urlzap_0.1.0_linux_amd64.tar.gz"
      sha256 "331bb00bfbd810e26bb009165286da9ce3a612c62af79ea8ddb93e8a04de22d4"
    end
  end

  def install
    bin.install "urlzap"
  end
end
