# This file was generated by GoReleaser. DO NOT EDIT.
class Urlzap < Formula
  desc ""
  homepage ""
  version "1.0.0"
  

  if OS.mac?
    url "https://github.com/brunoluiz/urlzap/releases/download/v1.0.0/urlzap_1.0.0_darwin_amd64.tar.gz"
    sha256 "8dd7ff471a1b7a0d1540056a1843fe8b4a4dba87f09d66804e61adeacbd11d70"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/brunoluiz/urlzap/releases/download/v1.0.0/urlzap_1.0.0_linux_amd64.tar.gz"
    sha256 "94c99d89919ff8af79932c669783f278f98a36e698c53e6c49d49a5f869bd90f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/brunoluiz/urlzap/releases/download/v1.0.0/urlzap_1.0.0_linux_arm64.tar.gz"
    sha256 "7aa6c5536028349b0a4c6ffdcf9d4ffb0fbccfefd48356907603dd551bff6272"
  end

  def install
    bin.install "urlzap"
  end
end
